# Generated by Django 5.2 on 2025-04-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_otp_is_conf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='tried',
            field=models.IntegerField(default=0),
        ),
    ]
